### ISSUE TITLE
database disk image is malformed 

### ISSUE THREAD

**Issue by nestarz** [rkusa/wasm-sqlite#1]
Hello !

Nice project, I would like to use wasm-sqlite to mimic D1 on Deno Deploy or any other V8 "serverless" workers.
I tried to edit your project for a basic test using Deno and localStorage but got the following error:

```
error: Uncaught (in promise) Error: failed to get next row: database disk image is malformed
      throw new Error(err);
            ^
    at SqliteConnection.throwLastError (file:///Users/sqlite-deploy/vfs.ts:217:13)
    at async SqliteConnection.queryRaw (file:///Users/sqlite-deploy/vfs.ts:267:7)
    at async file:///Users/sqlite-deploy/index.ts:32:20
```

The code:

```ts
import { Sqlite } from "./vfs.ts";

const sqlite = await Sqlite.instantiate({
  pageCount(): number {
    return self.pageCount;
  },
  async getPage(ix: number): Promise<Uint8Array> {
    const page =
      new Uint8Array(JSON.parse(await localStorage.getItem(ix))) ??
      new Uint8Array(4096);
    return page;
  },
  async putPage(ix: number, page: Uint8Array): Promise<void> {
    await localStorage.setItem(ix, JSON.stringify(Array.from(page)));
    self.pageCount = Math.max(self.pageCount, ix + 1);
  },
  async delPage(ix: number): Promise<void> {
    await localStorage.removeItem(ix);
    if (ix + 1 >= self.pageCount) {
      self.pageCount = ix;
    }
  },
});

localStorage.clear();
const conn = await sqlite.connect();
const create: T = await conn.queryRaw(`CREATE TABLE td(a INT) STRICT;`);
const insert: T = await conn.queryRaw(`INSERT INTO td VALUES('000123');`);
console.log(create, insert);
```

And the `vfs.ts` diff:

```ts
1c1,2
< import * as Asyncify from "https://unpkg.com/asyncify-wasm?module";
---
> import * as Asyncify from "asyncify-wasm";
> import module from "./wasm_sqlite.wasm";
23,24c24
<     const { instance } = await Asyncify.instantiateStreaming(
<         fetch(new URL("./wasm_sqlite.wasm", import.meta.url)), {
---
>     const instance = await Asyncify.instantiate(module, {
```

Do you have any clue why the database got corrupted ?

Best,

**Comment by rkusa** [comment]
I think it might be because your `self.` in `self.pageCount` isn't referring to anything. I can see that this is misleading as the example in the README isn't showing where it comes from.

Here is an example of where the `self` comes from in a complete implementation: https://github.com/rkusa/do-sqlite/blob/e46c39cc16586c2a74942ca2a725063ceb595ac5/src/worker.ts#L15

Let me know if the linked code isn't helping, I can shortly explain what happens there then.

**Comment by rkusa** [comment]
Another side-note. When using Deno, you might be able to replace the [custom wasi code](https://github.com/rkusa/wasm-sqlite/blob/main/src/lib.ts#L25-L132) with https://deno.land/std@0.147.0/wasi

**Comment by nestarz** [comment]
Thank you !! It worked with defining the `self` variable.
I pushed a version of your work here https://github.com/nestarz/sqlite-any where we can choose any storage provider.
Right now I'm using it with R2 from Cloudflare, and it works well, I dont know if it will leads to corrupted data in the long term, and I still need to test it on Deno Deploy.

I didn't understood how to integrate https://deno.land/std@0.147.0/wasi to replace `wasi_snapshot_preview1` as it seems to be custom code no ?

I tried keeping the essence of their example :

```ts
import Context from "https://deno.land/std@0.171.0/wasi/snapshot_preview1.ts";

const context = new Context({
  args: Deno.args,
  env: Deno.env.toObject(),
});

const binary = await Deno.readFile("path/to/your/module.wasm");
const module = await WebAssembly.compile(binary);
const instance = await WebAssembly.instantiate(module, {
  "wasi_snapshot_preview1": context.exports,
});

context.start(instance);
```

Here is the diff
```ts
1a2,7
> import Context from "https://deno.land/std@0.171.0/wasi/snapshot_preview1.ts";
> 
> const context = new Context({
>   args: Deno.args,
>   env: Deno.env.toObject(),
> });
33,145c39
<         wasi_snapshot_preview1: {
[truncated]
<         },
---
>         wasi_snapshot_preview1: context.exports,
174a69
>     context.start(instance);
```

But got 

`Uncaught (in promise) TypeError: WebAssembly.Instance export _start must be a function`

**Comment by rkusa** [comment]
I am glad you got it solved. Another hint for the `pageCount`. Make sure to either persist it between instantiations of your program, or restore it from the first page as done here: https://github.com/rkusa/do-sqlite/blob/e46c39cc16586c2a74942ca2a725063ceb595ac5/src/worker.ts#L18-L24

Regarding Deno's wasi: you need to use `Asyncify.instantiate` instead of `WebAssembly.instantiate`, and also keep the `env` imports here: https://github.com/rkusa/wasm-sqlite/blob/main/src/lib.ts#L134-L160

**Comment by nestarz** [comment]
Thanks, I did restored the pageCount anytime I start my program as seen here https://github.com/nestarz/sqlite-any/blob/9ed41a4b8ab825075dd4ec3efaf8f6b72710c626/mod.ts#L9.

It works well at first, but after a program restart it goes corrupted (?), all queries except SELECT produce an error:
```ts
import { Sqlite as VFS } from "./vfs.ts"; // https://raw.githubusercontent.com/nestarz/sqlite-any/main/vfs.ts

const Sqlite = async (
  get: (arg: number) => Promise<ArrayBuffer | void>,
  set: (arg: number, buffer: Array<number>) => Promise<boolean>,
  remove: (arg: number) => Promise<boolean>
) => {
  const state = { pageCount: 0 };
  const page = await get(0);
  if (page) {
    const view = new DataView(new Uint8Array(page).buffer);
    state.pageCount = view.getUint32(28, false);
  }
  console.log(state.pageCount);
  return await VFS.instantiate({
    pageCount(): number {
      return state.pageCount;
    },
    async getPage(ix: number): Promise<Uint8Array> {
      const page = new Uint8Array((await get(ix)) ?? new Uint8Array(4096));
      return page;
    },
    async putPage(ix: number, page: Uint8Array): Promise<void> {
      await set(ix, Array.from(page));
      state.pageCount = Math.max(state.pageCount, ix + 1);
    },
    async delPage(ix: number): Promise<void> {
      await remove(ix);
      if (ix + 1 >= state.pageCount) {
        state.pageCount = ix;
      }
    },
  });
};

const pageToS3Key = (page: number) => `${page}.sqlite.part`;
const get = (page: number) => 
    s3.getObject(pageToS3Key(page)).then((r) => r.arrayBuffer()).catch(console.warn);
const set = (page: number, buffer: number[]) => 
    s3.putObject(pageToS3Key(page), new Blob([new Uint8Array(buffer)]).stream());
const remove = (page: number) => s3.deleteObject(pageToS3Key(page));
const conn = await (await Sqlite(get, set, remove)).connect();

// first program execution:
await conn.query("CREATE TABLE users(id INTEGER) STRICT;").then(console.log); 
// -> works
await conn.query("INSERT INTO users (id) VALUES (2);").then(console.log).catch(console.warn); 
// -> works

// restart program and then execute:
await conn.query("INSERT INTO users (id) VALUES (2);").then(console.log).catch(console.warn); 
// Error: failed to get next row: unable to open database file
//    at SqliteConnection.throwLastError (https://deno.land/x/sqlite_any@0.0.1/vfs.ts:225:13)
//    at async SqliteConnection.queryRaw (https://deno.land/x/sqlite_any@0.0.1/vfs.ts:275:7)
//    at async SqliteConnection.query (https://deno.land/x/sqlite_any@0.0.1/vfs.ts:254:23)
await conn.query("SELECT * FROM users;").then(console.log).catch(console.warn); 
// -> works [ { id: 2 } ]
```

**Comment by rkusa** [comment]
I cannot spot an issue in the code. I'd be happy to look into it further if you can provide me a complete snippet to reproduce it by myself (by adding my own S3 endpoint/credentials and `deno` run it).

**Comment by nestarz** [comment]
Good morning @rkusa and thank you !

It doesn't have to be S3, it doesn't works with localStorage too, here a reproduction code:

`deno run -A main.ts`

```ts
// main.ts
import { Sqlite as VFS } from "https://deno.land/x/sqlite_any@0.0.1/vfs.ts";

const Sqlite = async (
  get: (arg: number) => Promise<ArrayBuffer | void>,
  set: (arg: number, buffer: Array<number>) => Promise<boolean>,
  remove: (arg: number) => Promise<boolean>
) => {
  const state = { pageCount: 0 };
  const page = await get(0);
  if (page) {
    const view = new DataView(new Uint8Array(page).buffer);
    state.pageCount = view.getUint32(28, false);
  }
  console.log(state.pageCount);
  return await VFS.instantiate(
    {
      pageCount(): number {
        return state.pageCount;
      },
      async getPage(ix: number): Promise<Uint8Array> {
        const page = new Uint8Array((await get(ix)) ?? new Uint8Array(4096));
        return page;
      },
      async putPage(ix: number, page: Uint8Array): Promise<void> {
        await set(ix, Array.from(page));
        state.pageCount = Math.max(state.pageCount, ix + 1);
      },
      async delPage(ix: number): Promise<void> {
        await remove(ix);
        if (ix + 1 >= state.pageCount) {
          state.pageCount = ix;
        }
      },
    },
    { isDebug: true }
  );
};

const pageToS3Key = (page: number) => `${page}.sqlite.part`;
const get = (page: number) =>
  JSON.parse(localStorage.getItem(pageToS3Key(page)) ?? "null");
const set = (page: number, buffer: number[]) =>
  localStorage.setItem(
    pageToS3Key(page),
    JSON.stringify(Array.from(new Uint8Array(buffer)))
  );
const remove = (page: number) => localStorage.removeItem(pageToS3Key(page));

if (Deno.args[0] !== "second_run") {
  localStorage.clear();
  const conn = await (await Sqlite(get, set, remove)).connect();
  await conn.query("CREATE TABLE users(id INTEGER) STRICT;").then(console.log);
  await conn.query("INSERT INTO users (id) VALUES (2);").then(console.log);
  await conn.query("SELECT * FROM users;").then(console.log);
  await conn.drop();
  const proc = await Deno.run({
    cmd: ["deno", "run", "-A", "main.ts", "second_run"],
  });
  await proc.status();
} else {
  const conn = await (await Sqlite(get, set, remove)).connect();
  await conn.query("INSERT INTO users (id) VALUES (2);").then(console.log);
  await conn.query("SELECT * FROM users;").then(console.log);
  await conn.drop();
  console.log("ok");
}

```


PS: [https://deno.land/x/sqlite_any/vfs.ts](https://deno.land/x/sqlite_any@0.0.1/vfs.ts) is only a minor modification of yours, here are the important diff:

```ts
1c1,2
< import * as Asyncify from "https://unpkg.com/asyncify-wasm?module";
---
> import * as Asyncify from "asyncify-wasm";
> import module from "./wasm_sqlite.wasm";
23,25c24
<     const { instance } = await Asyncify.instantiateStreaming(      
<     fetch(new URL("./wasm_sqlite.wasm", import.meta.url)),
<     {
---
>     const instance = await Asyncify.instantiate(module, {
```

**Comment by rkusa** [comment]
@nestarz thanks a lot for the reproducible example! It should be fixed in the latest version. The fix was to [set  `journal_mode=memory` for each connection](https://github.com/rkusa/wasm-sqlite/commit/6d2a66fb09ba19503c3531c3df2d42a6908be12b) (my own usage did that outside of the library, which is why I didn't notice it myself). I've also removed all the debug and trace logs and added a [`deno` branch](https://github.com/rkusa/wasm-sqlite/tree/deno) that shows how to use https://deno.land/std@0.176.0/wasi/snapshot_preview1.ts.
